services:
- type: pserv
  name: elasticsearch
  env: docker
  plan: standard
  disk:
    name: esdata
    mountPath: /usr/share/elasticsearch/data
    sizeGB: 10
  autoDeploy: false
  envVars:
  - key: cluster.name
    value: elastic
